<a href="https://colab.research.google.com/github/Nitish-kk/PCS221_Cloud-Infrastructure-and-Services/blob/main/Cloud_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Create a 20000 × 10000 data file using Python random module

In [1]:
import random
import csv

rows = 20000
cols = 10000

file_path = "/content/rows_columns.csv"

with open(file_path, "w", newline="") as f:
    writer = csv.writer(f)

    for r in range(rows):
        # different random parameters
        row = [random.randint(0, 1000) for _ in range(cols)]
        writer.writerow(row)

        if r % 100 == 0:
            print(f"{r} rows written...")

print("DATASET CREATED SUCCESSFULLY")


0 rows written...
100 rows written...
200 rows written...
300 rows written...
400 rows written...
500 rows written...
600 rows written...
700 rows written...
800 rows written...
900 rows written...
1000 rows written...
1100 rows written...
1200 rows written...
1300 rows written...
1400 rows written...
1500 rows written...
1600 rows written...
1700 rows written...
1800 rows written...
1900 rows written...
2000 rows written...
2100 rows written...
2200 rows written...
2300 rows written...
2400 rows written...
2500 rows written...
2600 rows written...
2700 rows written...
2800 rows written...
2900 rows written...
3000 rows written...
3100 rows written...
3200 rows written...
3300 rows written...
3400 rows written...
3500 rows written...
3600 rows written...
3700 rows written...
3800 rows written...
3900 rows written...
4000 rows written...
4100 rows written...
4200 rows written...
4300 rows written...
4400 rows written...
4500 rows written...
4600 rows written...
4700 rows written...
4800

2) Assign subsequent rows to matrix first row elements

In [2]:
import numpy as np

matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print("Original Matrix:\n", matrix)

first_row = matrix[0]

# assign first row to all rows
for i in range(1, matrix.shape[0]):
    matrix[i] = first_row

print("\nUpdated Matrix:\n", matrix)


Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Updated Matrix:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


3) Group similar elements into matrix

In [4]:
import numpy as np
from collections import defaultdict

matrix = np.array([
    [1,2,2],
    [3,1,4],
    [2,3,1]
])

groups = defaultdict(list)

for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        groups[matrix[i][j]].append((i,j))

print("Grouped Elements:")
for key, value in groups.items():
    print(f"Element {key} found at positions {value}")


Grouped Elements:
Element 1 found at positions [(0, 0), (1, 1), (2, 2)]
Element 2 found at positions [(0, 1), (0, 2), (2, 0)]
Element 3 found at positions [(1, 0), (2, 1)]
Element 4 found at positions [(1, 2)]


4) Add and Subtract matrices

In [5]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix A:\n",A)
print("Matrix B:\n",B)

# Addition
add = A + B
print("\nAddition:\n",add)

# Subtraction
sub = A - B
print("\nSubtraction:\n",sub)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]


5) Create n×n matrix where opposite corners sum is EVEN

In [6]:
import numpy as np

n = 5

matrix = np.random.randint(0,50,(n,n))*2  # only even numbers

print("Matrix:\n",matrix)

# verification
valid = True
for i in range(n):
    for j in range(n):
        if (matrix[i][j] + matrix[n-1-i][n-1-j]) % 2 != 0:
            valid = False

print("\nCondition satisfied:", valid)


Matrix:
 [[68  4 70 82 96]
 [34 92  2 30 12]
 [50 30 52 24 54]
 [70 18 46 74  0]
 [98 42 50 86 54]]

Condition satisfied: True


6) Row-wise element addition in tuple matrix

In [7]:
tuple_matrix = (
    (1,2,3),
    (4,5,6),
    (7,8,9)
)

row_sums = []

for row in tuple_matrix:
    row_sums.append(sum(row))

print("Row-wise sums:", row_sums)


Row-wise sums: [6, 15, 24]
